# Generated by Django 5.0.1 on 2024-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimodelo',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
