# Generated by Django 5.0.1 on 2024-01-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_mimodelo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, null=True)),
                ('tamanio', models.CharField(choices=[('bebe', 'Bebé'), ('joven', 'Joven'), ('adulto', 'Adulto')], default='Joven', max_length=7)),
                ('raza', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
